<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://services.idit.com" xmlns:interfaces-root="http://www.idit.co.il/schemas/all/interfaces-root" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://services.idit.com">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.idit.co.il/schemas/all/interfaces-root" schemaLocation="asosUpdateProposal.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IDITServicesANDLasosUpdateProposalResponse">
    <wsdl:part name="POutParam" element="interfaces-root:asosUpdateProposalResponseANDLIVOoutList"/>
  </wsdl:message>
  <wsdl:message name="IDITServicesANDLasosUpdateProposalRequest">
    <wsdl:part name="PInParam" element="interfaces-root:asosUpdateProposalRequestANDLIVOinList"/>
    <wsdl:part name="PInHeader" element="interfaces-root:basicSoapHeaderIVOinList"/>
  </wsdl:message>
  <wsdl:portType name="IDITServicesANDLasosUpdateProposalInterface">
    <wsdl:operation name="IDITServicesANDLasosUpdateProposal">
      <wsdl:input name="IDITServicesANDLasosUpdateProposalRequest" message="tns:IDITServicesANDLasosUpdateProposalRequest"/>
      <wsdl:output name="IDITServicesANDLasosUpdateProposalResponse" message="tns:IDITServicesANDLasosUpdateProposalResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IDITServicesANDLasosUpdateProposalSOAPHTTPBinding" type="tns:IDITServicesANDLasosUpdateProposalInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IDITServicesANDLasosUpdateProposal">
      <soap:operation soapAction="http://services.idit.com/IDITServicesANDLasosUpdateProposal"/>
      <wsdl:input>
        <soap:body use="literal" message="tns:IDITServicesANDLasosUpdateProposalRequest" parts="PInParam"/>
        <soap:header use="literal" message="tns:IDITServicesANDLasosUpdateProposalRequest" part="PInHeader"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IDITServicesANDLasosUpdateProposal">
    <wsdl:port name="IDITServicesANDLasosUpdateProposalInterface" binding="tns:IDITServicesANDLasosUpdateProposalSOAPHTTPBinding">
      <soap:address location="https://apitest.anadolusigorta.com.tr/api/agency/IDITServicesANDLasosUpdateProposal"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>